# 网站名称
title: 我的个人博客

# 网站描述
description: 这是我的博客网站，分享技术和生活

# 网站的URL地址
url: https://leochame.github.io

# 网站的基本路径，通常是空字符串，除非你的项目部署在子目录下
#baseurl: ""  # 如果GitHub Pages部署在子目录（例如https://username.github.io/repository），这里写“/repository”

# 网站的主题配置，选择Jekyll支持的主题
theme: minima

# 每个页面的默认布局
defaults:
  - scope:
      path: ""
    values:
      layout: "default"

# 你的站点作者信息
author:
  name: "Leo cham"
  email: "liulch.cn@gmail.com"

# 社交链接（GitHub、Twitter等）
social_links:
  github: https://github.com/leochame
  twitter: https://twitter.com/username
  linkedin: https://linkedin.com/in/username

# 站点配置，是否显示分页等
paginate: 10  # 每一页显示的文章数量

# 站点语言
locale: zh-CN  # 可以设置为中文

# 自定义菜单链接
menu:
  Home: /
  About: /about/
  Blog: /blog/
  Contact: /contact/

# 其他配置
markdown: kramdown  # 选择markdown渲染引擎，Jekyll默认使用kramdown
highlighter: pygments  # 代码高亮显示工具
exclude:
  - README.md
  - LICENSE
plugins:
  - jekyll-feed
  - jekyll-seo-tag
permalink: /:categories/:year/:month/:day/:title/

